import type { AtomicOperationV2, BattleBaseLocationV2, FieldZoneV2, GameEventV2, GameStateV2, PlayerIndex } from "../model";
import { effectiveValueV2 } from "../effects/atomicOps";
import { registerEffectV2, type EffectContextV2, type EffectDefinitionV2 } from "../effects/registry";

const fieldZones: readonly FieldZoneV2[] = ["vanguard", "flankLeft", "flankRight", "rear"];
const opponentOf = (actor: PlayerIndex): PlayerIndex => actor === 0 ? 1 : 0;
const battleRoles = (state: GameStateV2, actor: PlayerIndex): string[] => fieldZones.flatMap((zone) => state.players[actor].field[zone]);
const faceUpRoles = (state: GameStateV2, actor: PlayerIndex): string[] => [...battleRoles(state, actor), ...state.players[actor].baseCards];
const baseCount = (state: GameStateV2, actor: PlayerIndex): number => state.players[actor].baseCards.length + state.players[actor].baseCovered.length;
const hasFeature = (state: GameStateV2, cardId: string, feature: string): boolean => state.cards[cardId]?.features.some((value) => value.includes(feature)) ?? false;
const eventOf = <T extends GameEventV2["type"]>(context: EffectContextV2 | undefined, type: T): Extract<GameEventV2, { type: T }> | null => context?.triggerEvent?.type === type ? context.triggerEvent as Extract<GameEventV2, { type: T }> : null;
const selfPlaced = (context: EffectContextV2 | undefined, source: string): boolean => eventOf(context, "CHARACTER_PLACED")?.cardId === source;
const useKey = (source: string, effectId: string, index?: number): string => `${source}:${effectId}${index ? `:${index}` : ""}`;
const usedCount = (state: GameStateV2, source: string, effectId: string): number => state.usage.effectUseKeysThisTurn.filter((key) => key === useKey(source, effectId) || key.startsWith(`${useKey(source, effectId)}:`)).length;
const markUse = (state: GameStateV2, source: string, effectId: string, limit = 1): AtomicOperationV2 => ({ kind: "MARK_EFFECT_USED", key: limit === 1 ? useKey(source, effectId) : useKey(source, effectId, usedCount(state, source, effectId) + 1) });
const modifier = (source: string, target: string, type: "power" | "range" | "level", value: number, suffix: string, mode: "delta" | "replace" = "delta"): AtomicOperationV2 => ({ kind: "ADD_MODIFIER", modifier: { id: `starter:${source}:${suffix}:${target}`, sourceCardId: source, targetCardId: target, type, value, mode, duration: "turn" } });
const openFieldZones = (state: GameStateV2, actor: PlayerIndex): FieldZoneV2[] => fieldZones.filter((zone) => state.players[actor].field[zone].length === 0);
const zoneChoice = (zone: BattleBaseLocationV2): string => `zone:${zone}`;
const parseZone = (choice: string): BattleBaseLocationV2 => choice.replace(/^zone:/, "") as BattleBaseLocationV2;

function fieldZoneOf(state: GameStateV2, actor: PlayerIndex, cardId: string): FieldZoneV2 | null {
  return fieldZones.find((zone) => state.players[actor].field[zone].includes(cardId)) ?? null;
}

function battleBaseDestinations(state: GameStateV2, actor: PlayerIndex, cardId: string): BattleBaseLocationV2[] {
  if (state.usage.enteredThisTurn.includes(cardId) || state.usage.movedCardIds.includes(cardId)) return [];
  if (state.players[actor].baseCards.includes(cardId)) return openFieldZones(state, actor);
  return fieldZoneOf(state, actor, cardId) && baseCount(state, actor) < 6 ? ["base"] : [];
}

function movementTargeting(state: GameStateV2, actor: PlayerIndex, roles: string[]) {
  const movable = roles.filter((id) => battleBaseDestinations(state, actor, id).length > 0);
  const destinations = [...new Set(movable.flatMap((id) => battleBaseDestinations(state, actor, id)))];
  return { choices: [...movable, ...destinations.map(zoneChoice)], min: 2, max: 2, prompt: "选择 1 张角色及其战基移动目的地", choiceKind: "mixed" as const };
}

function validateMovement(state: GameStateV2, actor: PlayerIndex, selected: readonly string[]): string | null {
  const cards = selected.filter((id) => Boolean(state.cards[id]));
  const zones = selected.filter((id) => id.startsWith("zone:"));
  if (cards.length !== 1 || zones.length !== 1) return "必须选择 1 张角色和 1 个目的地";
  return battleBaseDestinations(state, actor, cards[0]).includes(parseZone(zones[0])) ? null : "该角色不能向所选位置进行战基移动";
}

function movementOperation(selected: readonly string[]): AtomicOperationV2 {
  return { kind: "MOVE_BATTLE_BASE", cardId: selected.find((id) => !id.startsWith("zone:"))!, destination: parseZone(selected.find((id) => id.startsWith("zone:"))!) };
}

function placementTargeting(state: GameStateV2, actor: PlayerIndex, cards: string[]) {
  const zones = openFieldZones(state, actor);
  if (cards.length === 1) return { choices: zones.map(zoneChoice), min: 1, max: 1, prompt: "点击 1 个空战区直接放置角色", choiceKind: "field_location" as const };
  return { choices: [...cards, ...zones.map(zoneChoice)], min: 2, max: 2, prompt: "选择 1 张角色及其放置战区", choiceKind: "mixed" as const };
}

function validatePlacement(state: GameStateV2, actor: PlayerIndex, cards: readonly string[], selected: readonly string[]): string | null {
  const chosenCards = selected.filter((id) => cards.includes(id));
  const chosenZones = selected.filter((id) => id.startsWith("zone:") && openFieldZones(state, actor).includes(parseZone(id) as FieldZoneV2));
  if (cards.length === 1 && selected.length === 1) return chosenZones.length === 1 ? null : "必须选择 1 个空战区";
  return chosenCards.length === 1 && chosenZones.length === 1 ? null : "必须选择 1 张合法角色和 1 个空战区";
}

function placedCardAndZone(selected: readonly string[], fixedCardId?: string): { cardId: string; destination: FieldZoneV2 } {
  return { cardId: fixedCardId ?? selected.find((id) => !id.startsWith("zone:"))!, destination: parseZone(selected.find((id) => id.startsWith("zone:"))!) as FieldZoneV2 };
}

function retreatedFromField(context: EffectContextV2 | undefined, source: string): boolean {
  const event = eventOf(context, "CARDS_RETREATED");
  return Boolean(event?.cardIds.includes(source) && (event.fromFieldCardIds?.includes(source) ?? ["battle", "state"].includes(event.reason)));
}

const definitions: EffectDefinitionV2[] = [
  { cardNo: "SD03-001", effectId: "supreme-watch-copy-power", label: "至高守望", trigger: "CHARACTER_PLACED", sourceZones: ["field", "base"], ruleRefs: ["301.41", "304.1"], eventFilter: (_s, _a, source, c) => selfPlaced(c, source), condition: (s, a) => faceUpRoles(s, opponentOf(a)).length > 0, targeting: (s, a) => ({ choices: faceUpRoles(s, opponentOf(a)), min: 1, max: 1, prompt: "选择敌方场上 1 张角色，获得其当前战力" }), buildOperations: (s, _a, source, targets) => [modifier(source, source, "power", effectiveValueV2(s, targets[0], "power"), "supreme-watch")] },
  { cardNo: "SD03-002", effectId: "wing-pressure", label: "折翼风压", trigger: "CHARACTER_PLACED", sourceZones: ["field", "base"], ruleRefs: ["301.12", "301.20", "301.32", "304.1"], eventFilter: (_s, _a, source, c) => selfPlaced(c, source), condition: (s, a) => ["flankLeft", "flankRight"].some((z) => s.players[opponentOf(a)].field[z as FieldZoneV2].some((id) => effectiveValueV2(s, id, "level") <= 4)) && baseCount(s, opponentOf(a)) < 6, targeting: (s, a) => ({ choices: [...s.players[opponentOf(a)].field.flankLeft, ...s.players[opponentOf(a)].field.flankRight].filter((id) => effectiveValueV2(s, id, "level") <= 4), min: 1, max: 1, prompt: "选择敌方侧翼区 1 张 Lv4 或以下角色移动至基地" }), buildOperations: (s, a, _source, targets) => [{ kind: "MOVE_TO_BASE", cardId: targets[0], face: "up" }, ...(baseCount(s, opponentOf(a)) >= 3 ? [{ kind: "COVER" as const, cardId: targets[0], requiresPreviousSuccess: true }] : [])] },
  { cardNo: "SD03-003", effectId: "emergency-call", label: "紧急号召", trigger: "BATTLE_BASE_MOVED", sourceZones: ["field", "base"], optional: true, ruleRefs: ["301.12", "301.18", "301.23", "301.32", "304.1"], eventFilter: (_s, _a, source, c) => eventOf(c, "BATTLE_BASE_MOVED")?.cardId === source, condition: (s, a) => s.players[a].hand.some((id) => hasFeature(s, id, "复仇者联盟")) && openFieldZones(s, a).length > 0, targeting: (s, a) => placementTargeting(s, a, s.players[a].hand.filter((id) => hasFeature(s, id, "复仇者联盟"))), validateTargets: (s, a, _source, selected) => validatePlacement(s, a, s.players[a].hand.filter((id) => hasFeature(s, id, "复仇者联盟")), selected), buildOperations: (_s, _a, source, selected) => { const placed = placedCardAndZone(selected); return [{ kind: "PLACE_FIELD", ...placed }, { kind: "RETREAT", cardIds: [source], requiresPreviousSuccess: true }]; } },
  { cardNo: "SD03-005", effectId: "battlefield-recovery", label: "战地回收", trigger: "BATTLE_BASE_MOVED", sourceZones: ["field", "base"], optional: true, usage: "turn_once", ruleRefs: ["301.20", "301.23", "304.1"], eventFilter: (_s, _a, source, c) => eventOf(c, "BATTLE_BASE_MOVED")?.cardId === source, condition: (s, a, source) => usedCount(s, source, "battlefield-recovery") === 0 && s.players[a].baseCovered.length > 0, targeting: (s, a) => ({ choices: s.players[a].baseCovered, min: 1, max: 1, prompt: "选择己方基地 1 张盖卡移回手牌" }), buildOperations: (s, _a, source, targets) => [{ kind: "RETURN_TO_HAND", cardIds: [targets[0]] }, markUse(s, source, "battlefield-recovery")] },
  { cardNo: "SD03-006", effectId: "grappling-arrow", label: "牵引箭", activation: "action", usage: "turn_once", sourceZones: ["field"], ruleRefs: ["301.13", "301.32", "304.2", "305.6"], canActivate: (s, _a, source) => usedCount(s, source, "grappling-arrow") === 0 && s.players[s.cards[source].owner].deck.length >= 3, buildOperations: (s, a, source) => [{ kind: "DISCARD_DECK_TOP", actor: a, count: 2 }, { kind: "DRAW", actor: a, count: 1, sourceCardId: source, requiresPreviousSuccess: true }, markUse(s, source, "grappling-arrow")] },
  { cardNo: "SD03-007", effectId: "quantum-siphon", label: "量子虹吸", trigger: "BATTLE_BASE_MOVED", sourceZones: ["field", "base"], optional: true, ruleRefs: ["301.14", "301.20", "301.23", "301.32", "304.1"], eventFilter: (_s, _a, source, c) => eventOf(c, "BATTLE_BASE_MOVED")?.cardId === source, condition: (s, a) => s.players[a].deck.length >= 3 && baseCount(s, a) <= 4, buildOperations: (s, a, source) => [{ kind: "BANISH", cardIds: [source] }, ...s.players[a].deck.slice(0, 3).map((cardId) => ({ kind: "MOVE_TO_BASE" as const, cardId, face: "down" as const, requiresPreviousSuccess: true }))] },
  { cardNo: "SD03-008", effectId: "freedom-inspiration", label: "自由鼓舞", activation: "action", sourceZones: ["field"], ruleRefs: ["301.20", "301.32", "301.41", "304.2"], canActivate: (s, a, source) => usedCount(s, source, "freedom-inspiration") < 2 && s.players[a].baseCovered.length > 0 && battleRoles(s, a).length > 0, targeting: (s, a) => ({ choices: [...s.players[a].baseCovered, ...battleRoles(s, a)], min: 2, max: 2, prompt: "选择 1 张己方基地盖卡撤退，并选择 1 张己方战区角色战力 +500" }), validateTargets: (s, a, _source, selected) => selected.filter((id) => s.players[a].baseCovered.includes(id)).length === 1 && selected.filter((id) => battleRoles(s, a).includes(id)).length === 1 ? null : "必须分别选择 1 张盖卡和 1 张战区角色", buildOperations: (s, a, source, selected) => { const base = selected.find((id) => s.players[a].baseCovered.includes(id))!; const role = selected.find((id) => battleRoles(s, a).includes(id))!; return [{ kind: "RETREAT", cardIds: [base] }, { ...modifier(source, role, "power", 500, `freedom-${usedCount(s, source, "freedom-inspiration") + 1}`), requiresPreviousSuccess: true }, markUse(s, source, "freedom-inspiration", 2)]; } },
  { cardNo: "SD03-009", effectId: "covering-fire-swap", label: "火力掩护", trigger: "CHARACTER_BATTLE_RESOLVED", sourceZones: ["field"], optional: true, usage: "turn_once", ruleRefs: ["301.18", "304.1"], eventFilter: (s, a, source, c) => { const e = eventOf(c, "CHARACTER_BATTLE_RESOLVED"); return Boolean(e?.winnerCardId && e.winnerCardId !== source && s.cards[e.winnerCardId]?.owner === a && battleRoles(s, a).includes(e.winnerCardId)); }, condition: (s, _a, source) => usedCount(s, source, "covering-fire-swap") === 0, buildOperations: (s, _a, source, _t, c) => [{ kind: "SWAP_POSITIONS", cardIds: [source, eventOf(c, "CHARACTER_BATTLE_RESOLVED")!.winnerCardId!] }, markUse(s, source, "covering-fire-swap")] },
  { cardNo: "SD03-010", effectId: "justice-from-above", label: "天降正义", trigger: "CHARACTER_PLACED", sourceZones: ["hand"], optional: true, ruleRefs: ["301.12", "304.1"], eventFilter: (s, a, _source, c) => { const e = eventOf(c, "CHARACTER_PLACED"); return Boolean(e && e.actor === opponentOf(a) && effectiveValueV2(s, e.cardId, "level") === 6); }, condition: (s, a) => openFieldZones(s, a).length > 0, targeting: (s, a, source) => placementTargeting(s, a, [source]), validateTargets: (s, a, source, selected) => validatePlacement(s, a, [source], selected), buildOperations: (_s, _a, source, selected) => [{ kind: "PLACE_FIELD", ...placedCardAndZone(selected, source) }] },
  { cardNo: "SD03-015", effectId: "noble-sacrifice", label: "杀身成仁", trigger: "ATTACK_DECLARED", sourceZones: ["hand"], optional: true, ruleRefs: ["301.14", "301.32", "303.2.a.4", "304.1"], eventFilter: (s, a, _source, c) => { const e = eventOf(c, "ATTACK_DECLARED"); return Boolean(e && e.actor === opponentOf(a) && effectiveValueV2(s, e.attackerId, "level") === 3 && battleRoles(s, a).reduce((n, id) => n + effectiveValueV2(s, id, "level"), 0) < battleRoles(s, opponentOf(a)).reduce((n, id) => n + effectiveValueV2(s, id, "level"), 0)); }, buildOperations: (_s, _a, source, _t, c) => [{ kind: "BANISH", cardIds: [source] }, { kind: "RETREAT", cardIds: [eventOf(c, "ATTACK_DECLARED")!.attackerId], requiresPreviousSuccess: true }] },
  { cardNo: "SD03-016", effectId: "quantum-entanglement", label: "量子纠缠", trigger: "ATTACK_DECLARED", sourceZones: ["hand"], optional: true, ruleRefs: ["301.25", "303.2.a.4", "304.1"], eventFilter: (s, a, _source, c) => { const e = eventOf(c, "ATTACK_DECLARED"); return Boolean(e && e.actor === opponentOf(a) && e.target.kind === "character" && s.cards[e.target.cardId]?.owner === a && s.cards[e.target.cardId]?.attribute === 3); }, buildOperations: (_s, _a, source, _t, c) => [{ kind: "ATTACH", cardId: source, hostCardId: eventOf(c, "ATTACK_DECLARED")!.attackerId }] },
  { cardNo: "SD03-017", effectId: "flash-arrow", label: "闪光箭", activation: "response", usage: "turn_once", sourceZones: ["field"], ruleRefs: ["301.13", "301.32", "301.41", "304.2"], canActivate: (s, a, source) => usedCount(s, source, "flash-arrow") === 0 && s.players[a].hand.some((id) => hasFeature(s, id, "复仇者联盟")) && battleRoles(s, opponentOf(a)).length > 0, targeting: (s, a) => ({ choices: [...s.players[a].hand.filter((id) => hasFeature(s, id, "复仇者联盟")), ...battleRoles(s, opponentOf(a))], min: 2, max: 2, prompt: "选择 1 张【复仇者联盟】手牌舍弃，并选择 1 张敌方战区角色战力 -1000" }), validateTargets: (s, a, _source, selected) => selected.filter((id) => s.players[a].hand.includes(id) && hasFeature(s, id, "复仇者联盟")).length === 1 && selected.filter((id) => battleRoles(s, opponentOf(a)).includes(id)).length === 1 ? null : "必须分别选择合法手牌和敌方角色", buildOperations: (s, a, source, selected) => { const hand = selected.find((id) => s.players[a].hand.includes(id))!; const enemy = selected.find((id) => battleRoles(s, opponentOf(a)).includes(id))!; return [{ kind: "DISCARD", cardIds: [hand] }, { ...modifier(source, enemy, "power", -1000, "flash-arrow"), requiresPreviousSuccess: true }, markUse(s, source, "flash-arrow")]; } },
  { cardNo: "SD03-018", effectId: "void-exile-banish", label: "虚空放逐·裁剪", trigger: "END_TRIGGERS_PROCESSED", sourceZones: ["field", "base"], optional: true, ruleRefs: ["301.14", "301.32", "303.2.a.6", "304.1"], eventFilter: (_s, a, _source, c) => eventOf(c, "END_TRIGGERS_PROCESSED")?.actor === a, condition: (s, a) => s.players[a].retreat.some((id) => s.cards[id]?.deckKind === "main") && faceUpRoles(s, a).some((id) => battleBaseDestinations(s, a, id).length > 0), targeting: (s, a) => ({ choices: s.players[a].retreat.filter((id) => s.cards[id]?.deckKind === "main"), min: 1, max: 1, prompt: "打开撤退区，选择 1 张角色裁剪" }), buildOperations: (_s, _a, source, targets) => [{ kind: "BANISH", cardIds: [targets[0]], sourceCardId: source }] },
  { cardNo: "SD03-018", effectId: "void-exile-move", label: "虚空放逐·战基移动", trigger: "CARDS_BANISHED", sourceZones: ["field", "base"], ruleRefs: ["301.23", "301.32", "304.1"], eventFilter: (_s, _a, source, c) => eventOf(c, "CARDS_BANISHED")?.sourceCardId === source, condition: (s, a) => faceUpRoles(s, a).some((id) => battleBaseDestinations(s, a, id).length > 0), targeting: (s, a) => movementTargeting(s, a, faceUpRoles(s, a)), validateTargets: (s, a, _source, selected) => validateMovement(s, a, selected), buildOperations: (_s, _a, _source, selected) => [movementOperation(selected)] },

  { cardNo: "SD04-001", effectId: "mischief-attach", label: "恶作剧之神", activation: "response", sourceZones: ["hand"], ruleRefs: ["301.25", "301.41", "304.2"], canActivate: (s) => ([0, 1] as const).some((a) => faceUpRoles(s, a).some((id) => hasFeature(s, id, "人类"))), targeting: (s) => ({ choices: ([0, 1] as const).flatMap((a) => faceUpRoles(s, a)).filter((id) => hasFeature(s, id, "人类")), min: 1, max: 1, prompt: "选择场上 1 张特征含有【人类】的角色" }), buildOperations: (_s, _a, source, targets) => [{ kind: "ATTACH", cardId: source, hostCardId: targets[0] }] },
  { cardNo: "SD04-002", effectId: "cluster-arrow", label: "集束箭", trigger: "CHARACTER_PLACED", sourceZones: ["field", "base"], ruleRefs: ["301.13", "301.32", "301.41", "304.1"], eventFilter: (_s, _a, source, c) => selfPlaced(c, source), condition: (s, a) => s.players[a].deck.length >= 2, targeting: (s, a) => { const enemies = battleRoles(s, opponentOf(a)); return { choices: enemies, min: enemies.length ? 1 : 0, max: enemies.length ? 1 : 0, prompt: enemies.length ? "选择敌方战区 1 张角色降低战力" : "敌方战区没有角色；仅舍弃卡组顶 2 张卡" }; }, buildOperations: (s, a, source, targets) => { const total = s.players[a].deck.slice(0, 2).reduce((n, id) => n + effectiveValueV2(s, id, "level"), 0); return [{ kind: "DISCARD_DECK_TOP", actor: a, count: 2 }, ...(targets[0] ? [{ ...modifier(source, targets[0], "power", -total * 1000, "cluster-arrow"), requiresPreviousSuccess: true }] : [])]; } },
  { cardNo: "SD04-003", effectId: "quantum-rewind", label: "量子回溯", trigger: "CARDS_RETREATED", sourceZones: ["retreat"], ruleRefs: ["301.14", "301.32", "304.1"], eventFilter: (_s, _a, source, c) => retreatedFromField(c, source), condition: (s, a) => battleRoles(s, a).length > 0 && battleRoles(s, opponentOf(a)).length > 0, targeting: (s, a) => { const own = battleRoles(s, a); const enemy = battleRoles(s, opponentOf(a)); const max = Math.max(...own.map((id) => effectiveValueV2(s, id, "level"))); const min = Math.min(...enemy.map((id) => effectiveValueV2(s, id, "level"))); return { choices: [...own.filter((id) => effectiveValueV2(s, id, "level") === max), ...enemy.filter((id) => effectiveValueV2(s, id, "level") === min)], min: 2, max: 2, prompt: "选择己方 Lv 最高角色和敌方 Lv 最低角色各 1 张移回手牌" }; }, validateTargets: (s, a, _source, selected) => { const own = battleRoles(s, a); const enemy = battleRoles(s, opponentOf(a)); return selected.filter((id) => own.includes(id)).length === 1 && selected.filter((id) => enemy.includes(id)).length === 1 ? null : "必须从双方合法极值角色中各选择 1 张"; }, buildOperations: (_s, _a, source, targets) => [{ kind: "BANISH", cardIds: [source] }, { kind: "RETURN_TO_HAND", cardIds: [...targets], requiresPreviousSuccess: true }] },
  { cardNo: "SD04-005", effectId: "quantum-teleport", label: "量子传态", trigger: "CARDS_RETREATED", sourceZones: ["retreat"], ruleRefs: ["301.14", "301.32", "304.1", "305.5"], eventFilter: (_s, _a, source, c) => retreatedFromField(c, source), condition: (s, a) => faceUpRoles(s, a).some((id) => effectiveValueV2(s, id, "level") <= 3), targeting: (s, a) => ({ choices: faceUpRoles(s, a).filter((id) => effectiveValueV2(s, id, "level") <= 3), min: 1, max: 1, prompt: "选择己方场上 1 张 Lv3 或以下角色，本回合获得【空袭】" }), buildOperations: (_s, _a, source, targets) => [{ kind: "BANISH", cardIds: [source] }, { kind: "GRANT_KEYWORD", grant: { id: `starter:${source}:quantum-teleport:${targets[0]}`, sourceCardId: source, targetCardId: targets[0], keyword: "airRaid", duration: "turn" }, requiresPreviousSuccess: true }] },
  { cardNo: "SD04-006", effectId: "covert-operation", label: "暗局运作", trigger: "BATTLE_BASE_MOVED", sourceZones: ["field", "base"], usage: "turn_once", ruleRefs: ["301.23", "301.32", "304.1"], eventFilter: (_s, _a, source, c) => eventOf(c, "BATTLE_BASE_MOVED")?.cardId === source, condition: (s, a, source) => usedCount(s, source, "covert-operation") === 0 && faceUpRoles(s, a).some((id) => hasFeature(s, id, "复仇者联盟")), targeting: (s, a) => ({ choices: faceUpRoles(s, a).filter((id) => hasFeature(s, id, "复仇者联盟")), min: 1, max: 1, prompt: "选择己方场上 1 张【复仇者联盟】角色移回手牌" }), buildOperations: (s, a, source, targets) => [{ kind: "RETURN_TO_HAND", cardIds: [targets[0]] }, { kind: "DRAW", actor: a, count: 1, sourceCardId: source, requiresPreviousSuccess: true }, markUse(s, source, "covert-operation")] },
  { cardNo: "SD04-007", effectId: "hydra-commander-move", label: "蛇首督军", activation: "action", usage: "turn_once", sourceZones: ["field", "base"], ruleRefs: ["301.23", "304.2"], canActivate: (s, a, source) => usedCount(s, source, "hydra-commander-move") === 0 && faceUpRoles(s, a).some((id) => battleBaseDestinations(s, a, id).length > 0), targeting: (s, a) => movementTargeting(s, a, faceUpRoles(s, a)), validateTargets: (s, a, _source, selected) => validateMovement(s, a, selected), buildOperations: (s, _a, source, selected) => [movementOperation(selected), markUse(s, source, "hydra-commander-move")] },
  { cardNo: "SD04-008", effectId: "strategic-retreat-zemo", label: "以退为进·泽莫", trigger: "CARDS_DISCARDED", sourceZones: ["retreat"], ruleRefs: ["301.13", "301.20", "301.32", "304.1"], eventFilter: (_s, _a, source, c) => eventOf(c, "CARDS_DISCARDED")?.cardIds.includes(source) ?? false, condition: (s, a) => s.players[a].deck.length >= 2 && baseCount(s, a) <= 4, buildOperations: (s, a) => s.players[a].deck.slice(0, 2).map((cardId) => ({ kind: "MOVE_TO_BASE" as const, cardId, face: "down" as const })) },
  { cardNo: "SD04-009", effectId: "strategic-retreat-captain", label: "以退为进·美国队长", trigger: "CARDS_DISCARDED", sourceZones: ["retreat"], optional: true, ruleRefs: ["301.12", "301.13", "301.20", "301.32", "304.1"], eventFilter: (_s, _a, source, c) => eventOf(c, "CARDS_DISCARDED")?.cardIds.includes(source) ?? false, condition: (s, a) => openFieldZones(s, a).length > 0 && s.players[opponentOf(a)].deck.length > 0 && baseCount(s, opponentOf(a)) < 6, targeting: (s, a, source) => placementTargeting(s, a, [source]), validateTargets: (s, a, source, selected) => validatePlacement(s, a, [source], selected), buildOperations: (s, a, source, selected) => [{ kind: "PLACE_FIELD", ...placedCardAndZone(selected, source) }, { kind: "MOVE_TO_BASE", cardId: s.players[opponentOf(a)].deck[0], face: "down", requiresPreviousSuccess: true }] },
  { cardNo: "SD04-011", effectId: "underground-voice", label: "地下之声", activation: "action", usage: "turn_once", sourceZones: ["field"], ruleRefs: ["301.41", "304.2"], canActivate: (s, a, source) => usedCount(s, source, "underground-voice") === 0 && battleRoles(s, a).length > 0, targeting: (s, a) => ({ choices: battleRoles(s, a), min: 1, max: 1, prompt: "选择己方战区 1 张角色，本回合 R 变为 2" }), buildOperations: (s, _a, source, targets) => [modifier(source, targets[0], "range", 2, "underground-voice", "replace"), markUse(s, source, "underground-voice")] },
  { cardNo: "SD04-014", effectId: "fair-justice", label: "公平正义", trigger: "CARDS_DISCARDED", sourceZones: ["retreat"], optional: true, ruleRefs: ["301.13", "301.18", "304.1"], eventFilter: (_s, _a, source, c) => eventOf(c, "CARDS_DISCARDED")?.cardIds.includes(source) ?? false, condition: (s, a) => battleRoles(s, a).some((id) => effectiveValueV2(s, id, "level") === 6), targeting: (s, a) => ({ choices: battleRoles(s, a).filter((id) => effectiveValueV2(s, id, "level") === 6), min: 1, max: 1, prompt: "选择己方场上 1 张 Lv6 角色与此卡互相替换" }), buildOperations: (_s, _a, source, targets) => [{ kind: "SWAP_POSITIONS", cardIds: [source, targets[0]] }] },
  { cardNo: "SD04-015", effectId: "quantum-gate", label: "量子门", trigger: "CARDS_RETREATED", sourceZones: ["retreat"], ruleRefs: ["301.14", "301.23", "301.32", "304.1"], eventFilter: (_s, _a, source, c) => retreatedFromField(c, source), condition: (s, a) => faceUpRoles(s, a).some((id) => battleBaseDestinations(s, a, id).length > 0), targeting: (s, a) => movementTargeting(s, a, faceUpRoles(s, a)), validateTargets: (s, a, _source, selected) => validateMovement(s, a, selected), buildOperations: (_s, _a, source, selected) => [{ kind: "BANISH", cardIds: [source] }, { ...movementOperation(selected), requiresPreviousSuccess: true }] },
  { cardNo: "SD04-017", effectId: "hit-and-run", label: "打带跑", trigger: "BATTLE_BASE_MOVED", sourceZones: ["field", "base"], ruleRefs: ["301.23", "301.41", "304.1"], eventFilter: (_s, _a, source, c) => eventOf(c, "BATTLE_BASE_MOVED")?.cardId === source, condition: (s, a) => battleRoles(s, opponentOf(a)).length > 0, targeting: (s, a) => ({ choices: battleRoles(s, opponentOf(a)), min: 1, max: 1, prompt: "选择敌方战区 1 张角色，本回合战力 -1000" }), buildOperations: (_s, _a, source, targets) => [modifier(source, targets[0], "power", -1000, "hit-and-run")] },
  { cardNo: "SD04-018", effectId: "run-and-search-draw", label: "跑带搜·抽牌", trigger: "BATTLE_BASE_MOVED", sourceZones: ["field", "base"], ruleRefs: ["301.13", "301.23", "301.32", "304.1"], eventFilter: (_s, _a, source, c) => eventOf(c, "BATTLE_BASE_MOVED")?.cardId === source, condition: (s, a) => s.players[a].deck.length > 0, buildOperations: (_s, a, source) => [{ kind: "DRAW", actor: a, count: 1, sourceCardId: source }] },
  { cardNo: "SD04-018", effectId: "run-and-search-discard", label: "跑带搜·舍弃", trigger: "TURN_CARDS_DRAWN", sourceZones: ["field", "base"], ruleRefs: ["301.13", "301.32", "304.1"], eventFilter: (_s, _a, source, c) => eventOf(c, "TURN_CARDS_DRAWN")?.sourceCardId === source, condition: (s, a) => s.players[a].hand.length > 0, targeting: (s, a) => ({ choices: s.players[a].hand, min: 1, max: 1, prompt: "选择抽牌后的 1 张手牌舍弃" }), buildOperations: (_s, _a, _source, targets) => [{ kind: "DISCARD", cardIds: [targets[0]] }] },
];

export function registerStarterEffectsSd03Sd04V2(): void {
  for (const definition of definitions) registerEffectV2(definition);
}

export const STARTER_EFFECT_DEFINITIONS_SD03_SD04_V2: readonly EffectDefinitionV2[] = definitions;
